OLED_ENABLE = no
ENCODER_ENABLE = no		  # Enables the use of one or more encoders
RGB_MATRIX_ENABLE = no    # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
SPLIT_KEYBOARD = yes      # ??
SERIAL_DRIVER = vendor    # ??
BOOTLOADER = rp2040
#CONVERT_TO = promicro_rp2040
MCU = RP2040
SPLIT_TRANSPORT = serial
USE_SERIAL = yes
CONSOLE_ENABLE = yes
